server:
  port: 8282

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8181/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: front-project-service-sum
        uri: lb://service-sum
        predicates:
        - Path=/sum/**
      - id: front-project-service-average
        uri: lb://service-average
        - Path=/average/**
